# Generated by Django 5.0.4 on 2024-05-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(blank=True, max_length=100, null=True)),
                ('des', models.TextField(blank=True, null=True)),
                ('file_upload', models.ImageField(blank=True, null=True, upload_to='file_upload')),
            ],
        ),
    ]
