# Generated by Django 5.0.4 on 2024-05-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='cn',
            new_name='Categoryname',
        ),
        migrations.RenameField(
            model_name='category_db',
            old_name='des',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='category_db',
            old_name='file_upload',
            new_name='Fileupload',
        ),
    ]
