# Generated by Django 5.0.4 on 2024-05-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_rename_cn_category_db_categoryname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='Categoryname',
            new_name='CategoryName',
        ),
    ]
