# Generated by Django 5.0.4 on 2024-05-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_categoryname_category_db_categoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='ProductImage')),
            ],
        ),
    ]
