# Generated by Django 5.0.4 on 2024-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registration_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_db',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
