# Generated by Django 5.0.4 on 2024-06-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_place_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_orderdb',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
